name: Latest blog post workflow
on:
  push:
  schedule:
    # Runs every hour
    - cron: "0 19 * * 1"

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://onhernandes.dev/index.xml"
